In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('placement.csv')

In [30]:
df.sample(10)

,cgpa,package
52,8.37,4.11
193,4.57,1.94
30,7.36,3.26
11,6.61,2.60
3,7.42,3.67
164,9.06,3.82
124,6.06,2.31
63,9.16,4.25
151,6.12,2.76
88,4.73,1.48


In [25]:
class LR:
    def __init__(self):
        self.b=None
        self.m=None

    def fit(self,x_train,y_train):
        num=0
        den=0
    
        for i in range (x_train.shape[0]):
            num=num+((x_train[i]-x_train.mean())*(y_train[i]-y_train.mean()))
            den=den+((x_train[i]-x_train.mean())*(x_train[i]-x_train.mean()))

        self.m=(num/den)
        self.b=y_train.mean()-(self.m * x_train.mean())

        print(self.m)
        print(self.b)


    def predict(self,x_test):
        return (self.m) * x_test + self.b
    
    

In [4]:
from sklearn.model_selection import train_test_split



In [16]:
x=df.iloc[:,0:1].values
y=df.iloc[:,1:2].values

array([[6.89],
       [5.12],
       [7.82],
       [7.42],
       [6.94],
       [7.89],
       [6.73],
       [6.75],
       [6.09],
       [8.31],
       [5.32],
       [6.61],
       [8.94],
       [6.93],
       [7.73],
       [7.25],
       [6.84],
       [5.38],
       [6.94],
       [7.48],
       [7.28],
       [6.85],
       [6.14],
       [6.19],
       [6.53],
       [7.28],
       [8.31],
       [5.42],
       [5.94],
       [7.15],
       [7.36],
       [8.1 ],
       [6.96],
       [6.35],
       [7.34],
       [6.87],
       [5.99],
       [5.9 ],
       [8.62],
       [7.43],
       [9.38],
       [6.89],
       [5.95],
       [7.66],
       [5.09],
       [7.87],
       [6.07],
       [5.84],
       [8.63],
       [8.87],
       [9.58],
       [9.26],
       [8.37],
       [6.47],
       [6.86],
       [8.2 ],
       [5.84],
       [6.6 ],
       [6.92],
       [7.56],
       [5.61],
       [5.48],
       [6.34],
       [9.16],
       [7.36],
       [7.6 ],
       [5.

In [18]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [26]:
lc=LR()

In [27]:
lc.fit(x_train,y_train)

[0.55795197]
[-0.89611192]


In [28]:
lc.predict(8.8)

array([4.01386544])

In [ ]:
y_pred=lc.predict(x_test)


array([[3.89111601],
       [3.09324469],
       [2.38464568],
       [2.57434935],
       [1.6537286 ],
       [1.77647803],
       [2.07219258],
       [2.93143862],
       [3.76278706],
       [2.93701814],
       [4.09197872],
       [3.51170867],
       [2.97049525],
       [2.40138424],
       [3.18809652],
       [3.46707251],
       [1.94386362],
       [3.24389172],
       [2.97607477],
       [3.41685683],
       [2.55761079],
       [3.16577844],
       [2.85890486],
       [3.12114229],
       [3.68467378],
       [2.8700639 ],
       [3.49497011],
       [3.34432308],
       [3.91901361],
       [1.96060218],
       [3.65119666],
       [3.2104146 ],
       [3.74046898],
       [2.7863711 ],
       [2.78079158],
       [3.27178932],
       [3.52844723],
       [2.61340599],
       [2.65804215],
       [2.71383735]])

In [35]:
y_test

array([[4.1 ],
       [3.49],
       [2.08],
       [2.33],
       [1.94],
       [1.48],
       [1.86],
       [3.09],
       [4.21],
       [2.87],
       [3.65],
       [4.  ],
       [2.89],
       [2.6 ],
       [2.99],
       [3.25],
       [1.86],
       [3.67],
       [2.37],
       [3.42],
       [2.48],
       [3.65],
       [2.6 ],
       [2.83],
       [4.08],
       [2.56],
       [3.58],
       [3.81],
       [4.09],
       [2.01],
       [3.63],
       [2.92],
       [3.51],
       [1.94],
       [2.21],
       [3.34],
       [3.34],
       [3.23],
       [2.01],
       [2.61]])