In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5,6])

In [3]:
print(arr)

[1 2 3 4 5 6]


In [4]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.zeros((4,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.linspace(1,5,3)

array([1., 3., 5.])

In [13]:
import random

In [14]:
np.random.rand(5)

array([0.75112908, 0.50402283, 0.64370259, 0.05254913, 0.16930595])

In [22]:
temparr=np.random.randint(10,60,12)

In [18]:
temparr.shape

(12,)

In [19]:
temparr.dtype

dtype('int32')

In [20]:
temparr.min()

np.int32(15)

In [24]:
arr=np.random.randint(10,60,12)
print(arr)

[24 25 34 15 42 57 18 44 40 38 17 25]


In [25]:
arr.min()

np.int32(15)

In [26]:
arr.max()

np.int32(57)

In [27]:
arr.sum()

np.int64(379)

In [28]:
arr.mean()

np.float64(31.583333333333332)

In [29]:
arr.std()

np.float64(12.392594114586698)

In [30]:
arr.argmax()

np.int64(5)

In [41]:
arr=np.arange(1,31)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [40]:
arr = arr.reshape(6,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [38]:
arr[2:4,0:3]

array([[11, 12, 13],
       [16, 17, 18]])

In [43]:
arr2=arr.reshape(6,5)
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [44]:
arr2[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [45]:
arr2[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [62]:

arrr=np.arange(1,31)

In [63]:
boalean_array=(arrr > 10) & (arrr%2==0)

In [64]:
arrr=arr[boalean_array]
print(arrr)

[12 14 16 18 20 22 24 26 28 30]


In [65]:
a1=np.random.randint(4,56,5)
a2=np.random.randint(4,56,5)

In [66]:
print(a1)
print(a2)

[20 31 20 21 53]
[33 22  6 20 19]


In [67]:
a1+a2

array([53, 53, 26, 41, 72], dtype=int32)

In [68]:
a1*a2

array([ 660,  682,  120,  420, 1007], dtype=int32)

In [69]:
a1-a2

array([-13,   9,  14,   1,  34], dtype=int32)

In [70]:
a1/a2

array([0.60606061, 1.40909091, 3.33333333, 1.05      , 2.78947368])

In [71]:
a1**a2

array([          0,  1244764481,    64000000, -1389842319, -1216928435],
      dtype=int32)

In [73]:
a1+10

array([30, 41, 30, 31, 63], dtype=int32)

In [74]:
a1*2

array([ 40,  62,  40,  42, 106], dtype=int32)